version: "2"
services:
  pastehunter:
    build: .
    container_name: pastehunter
    volumes:
      - ./logs:/usr/src/pastehunter/logs
      - ~/.config/pastehunter.json:/root/.config/pastehunter.json
    networks:
      esnet:
        ipv4_address: 172.16.10.11
    depends_on:
      - "elasticsearch"
      - "kibana"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      esnet:
        ipv4_address: 172.16.10.10

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      esnet:
        ipv4_address: 172.16.10.12
    depends_on:
      - "elasticsearch"

volumes:
  esdata1:

networks:
  esnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.10.0/24
      
